server:
  port: 7864

spring:
  application:
      name: service-client
  datasource:
      username: root
      password: 12345678
      url: jdbc:mysql://192.168.89.54:3306/test?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60
  client:
    serviceUrl:
      defaultZone: http://192.168.89.54:7861/eureka/v2,http://192.168.89.122:7861/eureka/v2,http://192.168.109.32:7861/eureka/v2


#http://192.168.109.32:7860/eureka/,http://192.168.89.54:7860/eureka/
#http://localhost:8080/eureka/v2/
#续约更新时间   lease-renewal-interval-in-seconds
#到期时间 lease-expiration-duration-in-seconds