server:
  port: 7864

spring:
  application:
      name: service-client

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/v2/
#http://192.168.109.32:7860/eureka/,