server:
  port: 7863

spring:
  application:
      name: service-client1

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:7860/eureka/

security:
  oauth2:
    resource:
      id: service-client
      user-info-uri: http://localhost:7869/uaa/user
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG