eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:7860/eureka/

server:
  port: 7862

spring:
  application:
      name: service-client
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379

jdbc:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678


security:
  oauth2:
    resource:
      id: service-client
      user-info-uri: http://localhost:7869/uaa/user
      prefer-token-info: false

logging.level.org.springframework.security: DEBUG
