server:
  port: 7861

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7861/eureka/
    use-dns-for-fetching-service-urls: false
    region: unavailable-region
spring:
  http:
    encoding:
      force: false
  application:
    name: eureka-server

#  spring.http.encoding.force=false

