eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.109.32:7860/eureka/,http://192.168.89.54:7860/eureka/

server:
  port: 7861

management.security.enabled: false

spring:
  application:
      name: service-ribbon
