server:
  port: 7866

spring:
  application:
      name: service-token
  redis:
    database: 5
    host: 192.168.88.196
    password: 123456
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 50
        max-idle: 500
        max-active: 2000
        max-wait: 1000


eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://192.168.88.196:7861/eureka/v2

##http://192.168.89.122:7861/eureka/v2