eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.89.54:7861/eureka/v2

server:
  port: 7869

spring:
  application:
    name: service-zuul
  redis:
    database: 5
    host: 192.168.89.54
    password: 123456
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 50
        max-idle: 500
        max-active: 2000
        max-wait: 1000

zuul:
  routes:
   api-a:
      path: /api-a/**
      sensitiveHeaders:
      serviceId: service-client
   token:
      path: /token/**
      sensitiveHeaders:
      serviceId: service-token
  add-proxy-headers: false
