eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7860/eureka/

server:
  port: 7869

spring:
  application:
    name: service-zuul

zuul:
  routes:
   uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: service-oauth
   api-a:
      path: /api-a/**
      sensitiveHeaders:
      serviceId: service-ribbon
  add-proxy-headers: true

security:
    oauth2:
      client:
            access-token-uri: http://localhost:7869/uaa/oauth/token
            user-authorization-uri: http://localhost:7869/uaa/oauth/authorize
            client-id: webapp
      resource:
        user-info-uri: http://localhost:7869/uaa/user
        prefer-token-info: false