server:
  port: 7860

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.109.32:7860/eureka/
    use-dns-for-fetching-service-urls: false
    region: unavailable-region
  server:
    peer-eureka-status-refresh-time-interval-ms: 10


spring:
  http:
    encoding:
      force: false
  application:
    name: eureka-server

